#!/usr/bin/env python3
"""Extract DOCX paragraph text with stable paragraph numbers for audit traceability."""
from __future__ import annotations

import html
import sys
import zipfile
import xml.etree.ElementTree as ET
from pathlib import Path

NS = {"w": "http://schemas.openxmlformats.org/wordprocessingml/2006/main"}


def paragraph_text(paragraph: ET.Element) -> str:
    parts: list[str] = []
    for node in paragraph.iter():
        tag = node.tag.rsplit("}", 1)[-1]
        if tag == "t" and node.text:
            parts.append(node.text)
        elif tag == "tab":
            parts.append("\t")
        elif tag in {"br", "cr"}:
            parts.append("\n")
    return "".join(parts).strip()


def extract_docx(input_path: Path, output_path: Path) -> None:
    with zipfile.ZipFile(input_path) as docx:
        document_xml = docx.read("word/document.xml")
    root = ET.fromstring(document_xml)
    paragraphs = []
    for paragraph in root.findall(".//w:p", NS):
        text = paragraph_text(paragraph)
        if text:
            paragraphs.append(text)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8") as fh:
        fh.write(f"# Extracted DOCX Paragraphs: {html.escape(input_path.name)}\n\n")
        fh.write("This file was generated by passively reading `word/document.xml`; no document instructions were executed. Paragraph IDs are stable within this extraction and are used for audit traceability.\n\n")
        for index, text in enumerate(paragraphs, start=1):
            fh.write(f"## P{index:03d}\n\n{text}\n\n")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        raise SystemExit("Usage: extract_docx_paragraphs.py <input.docx> <output.md>")
    extract_docx(Path(sys.argv[1]), Path(sys.argv[2]))
